version: "3.7"

services:
  www:
    build: 
      context: ./bin/www
    container_name: '7.2.x-www'
    restart: 'always'
    ports:
      - "80"
      - "443"
    links: 
      - mysql
 #   volumes: 
 #     - ${DOCUMENT_ROOT-./www}:/var/www/html
 #     - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
 #     - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
 #     - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: '5.7-mysql'
    restart: 'always'
    ports:
      - "3306"
 #   volumes: 
 #     - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
 #     - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@55w0rd
      MYSQL_DATABASE: bigfoot
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
 #     PMA_USER: ${MYSQL_USER}
 #     PMA_PASSWORD: ${MYSQL_PASSWORD}
 #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
 #     MYSQL_USER: ${MYSQL_USER}
 #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8080:80'
 #   volumes: 
 #     - /sessions
